server:
  servlet:
    context-path: /api

spring:
  redis:
    cluster:
      nodes: 172.20.10.32:6379,172.20.10.33:6379,172.20.10.37:6379
      max-redirects: 5
    password: nashwork3806
    timeout: 5000
    lettuce:
      pool:
        max-idle: 8
        max-active: 500
        max-wait: 3000
  devtools:
    restart:
      enabled:  false
  database-platform: org.hibernate.dialect.MySQL57InnoDBDialect


info:
  app:
    name: @project.artifactId@
    version: @project.version@
    groupId: @project.groupId@
    url: @project.url@


curator:
  baseSleepTimeMs: 2000
  maxRetries: 3
  maxSleepMs: 1000
  connectString: 192.168.171.131:2181,192.168.171.131:2182,192.168.171.131:2183
  sessionTimeoutMs: 2000
  connectionTimeoutMs: 3000
  nameSpace: spring


logging:
  config: classpath:logback.xml

mybatis:
  typeAliasesPackage: com.spring.start.entity
  mapperLocations:  classpath:mapper/*.xml


sharding:
  jdbc:
    datasource:
      names: test0,test1,test2,test3
      test0: # 配置主库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test0?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
      test1: # 配置第一个从库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
      test2: # 配置第二个从库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
      test3: # 配置第二个从库
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test3?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
      sharding:
        #defaultDataSourceName: test0
        master-slave-rules:
          ds0:
            master-data-source-name: test0
            slave-data-source-names: test1
          ds1:
            master-data-source-name: test2
            slave-data-source-names: test3
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: ds$->{id %2}
        tables:
          order:
            actual-data-nodes: ds$->{0..1}.order$->{0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: order$->{order_id%2}
      props:
        sql:
          show: true

#mybatis
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.spring.start.entity
#  global-config:
#    # 数据库相关配置
#    db-config:
#      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: id_worker
#      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
#      #驼峰下划线转换
#      column-underline: true
#      #数据库大写下划线转换
#      #capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      db-type: h2
#    #刷新mapper 调试神器
#    refresh: true
#  # 原生配置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false